# Generated by Django 4.1.5 on 2023-01-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('job', models.CharField(max_length=30, verbose_name='Que hace?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
        ),
    ]
