# Generated by Django 4.1.5 on 2023-01-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='since',
            field=models.DateField(null='01/01/2000'),
            preserve_default='01/01/2000',
        ),
    ]
