# Generated by Django 4.1.4 on 2023-01-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='since',
            field=models.DateField(null='01/01/2000', verbose_name='Desde'),
        ),
    ]
