# Generated by Django 4.1.4 on 2023-02-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_since'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
    ]
