# Generated by Django 4.1.5 on 2023-01-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='more_pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vaccine', models.BooleanField()),
                ('birth', models.DateField()),
                ('adoption_date', models.DateField()),
                ('castrated', models.BooleanField()),
            ],
        ),
    ]
