# Generated by Django 4.1.5 on 2023-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0002_more_pets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'verbose_name': 'Gato', 'verbose_name_plural': 'Gatos'},
        ),
        migrations.AlterModelOptions(
            name='dogs',
            options={'verbose_name': 'Perro', 'verbose_name_plural': 'Perros'},
        ),
        migrations.AlterModelOptions(
            name='more_pets',
            options={'verbose_name': 'Otros', 'verbose_name_plural': 'Otros'},
        ),
        migrations.AlterField(
            model_name='cats',
            name='adoption_date',
            field=models.DateField(verbose_name='Fecha de adopción'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='birth',
            field=models.DateField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='castrated',
            field=models.BooleanField(verbose_name='Castrado'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='vaccine',
            field=models.BooleanField(verbose_name='Vacunado'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='adoption_date',
            field=models.DateField(verbose_name='Fecha de adopción'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='birth',
            field=models.DateField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='castrated',
            field=models.BooleanField(verbose_name='Castrado'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='vaccine',
            field=models.BooleanField(verbose_name='Vacunado'),
        ),
        migrations.AlterField(
            model_name='more_pets',
            name='adoption_date',
            field=models.DateField(verbose_name='Fecha de adopción'),
        ),
        migrations.AlterField(
            model_name='more_pets',
            name='birth',
            field=models.DateField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='more_pets',
            name='castrated',
            field=models.BooleanField(verbose_name='Castrado'),
        ),
        migrations.AlterField(
            model_name='more_pets',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='more_pets',
            name='vaccine',
            field=models.BooleanField(verbose_name='Vacunado'),
        ),
    ]
