# Generated by Django 4.1.5 on 2023-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0004_remove_cats_adoption_date_remove_cats_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='castrated',
            field=models.BooleanField(default=False, verbose_name='Castrado'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='vaccine',
            field=models.BooleanField(default=False, verbose_name='Vacunado'),
        ),
    ]
