# Generated by Django 4.1.4 on 2023-02-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0007_alter_dogs_castrated_alter_dogs_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
