# Generated by Django 4.1.4 on 2023-02-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0008_dogs_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='birth_date',
        ),
    ]
