# Generated by Django 4.1.4 on 2023-02-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interested_in_adopting',
            field=models.BooleanField(default=False, verbose_name='Interesado en adoptar'),
        ),
    ]
